# [package]
# name = "recoil"
# version = "0.1.0"
# edition = "2024"

[workspace]
members = ["recoil-client", "recoil-coordinator", "recoil-errors"]
exclude = ["examples/ecommerce-example"]
resolver = "2"

[workspace.dependencies]
