[package]
name = "orders-service"
version = "0.1.0"
edition = "2024"

[workspace]
members = [".", "src", "migration"]

[workspace.dependencies]
tokio = { version = "1.44.2", features = ["macros", "rt-multi-thread"] }
sea-orm = { version = "1.1.0", features = ["sqlx-postgres", "tokio", "macros"] }
