[package]
name = "products-service"
version = "0.1.0"
edition = "2024"

[workspace]
members = [".", "src"]

[workspace.dependencies]
tokio = { version = "1.44.2", features = ["macros", "rt-multi-thread"] }
